services:
    api:
        env_file: ".env"
        build:
            context: .
            dockerfile: Dockerfile
        image: resepin-be
        volumes:
            - .:/app
        command:
            ["php", "artisan", "octane:start", "--host=0.0.0.0", "--port=8080"]
        restart: unless-stopped
        working_dir: /app
        ports:
            - 8081:8080
        networks:
            - resepin-gluton_default

networks:
    resepin-gluton_default:
        external: true
